#!/usr/bin/env python3
"""Ghidra Import Script for ICO Analysis.

This script generates a Ghidra script that can be used to quickly
navigate to known function addresses after importing the ELF.
"""

from pathlib import Path
import json

KNOWN_FUNCTIONS = [
    {"address": "0x001321c8", "description": "References DFDATAS (stack: 464 bytes)"},
    {"address": "0x00132630", "description": "Most called function - likely file I/O utility (stack: 704 bytes)"},
    {"address": "0x00132ff0", "description": "References DFDATAS (stack: 592 bytes)"},
    {"address": "0x00185ca8", "description": "References 0x00633b68 (stack: 320 bytes)"},
    {"address": "0x0019fb34", "description": "References 0x006127e8 - data loading (stack: 112 bytes)"},
    {"address": "0x001a0a38", "description": "References 0x00633b68 (stack: 176 bytes)"},
    {"address": "0x0023d468", "description": "References 0x00633b68 (stack: 320 bytes)"},
]

KNOWN_STRINGS = [
    {"address": "0x00556a28", "string": "DATA.DF"},
    {"address": "0x00556a10", "string": "DFDATAS"},
    {"address": "0x00556a20", "string": "DFDATAS"},
]


def generate_ghidra_script() -> str:
    script = '''// Ghidra Script for ICO Analysis
// Generated by ico-reconstruction tools

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;

public class ICOAnalysisScript extends GhidraScript {

    @Override
    public void run() throws Exception {
        println("=== ICO Analysis Setup ===");

        // Navigate to known functions
        println("\\n--- Known Functions ---");
'''

    for func in KNOWN_FUNCTIONS:
        addr = func["address"].replace("0x", "")
        script += f'        try {{\n'
        script += f'            Address addr = getAddressFactory().getAddress("0x{addr}");\n'
        script += f'            if (addr != null) {{\n'
        script += f'                println("Function: {func["description"]}");\n'
        script += f'                gotoAddress(addr);\n'
        script += f'            }}\n'
        script += f'        }} catch (Exception e) {{\n'
        script += f'            println("Failed to navigate to {func["address"]}: " + e.getMessage());\n'
        script += f'        }}\n'

    script += '''
        println("\\n=== Setup Complete ===");
    }
}
'''
    return script


def generate_markdown_guide() -> str:
    guide = '''# Ghidra Import Guide for ICO

## Prerequisites

1. Download Ghidra from: https://github.com/NationalSecurityAgency/ghidra
2. Extract the ZIP file
3. Run `./ghidra` to launch the GUI

## Import Steps

### 1. Import the ELF

1. Launch Ghidra
2. File → Import File
3. Navigate to: `.local/extracted/SCUS_971.13.elf`
4. Configure options:
   - Language: `MIPS:LE:32:GCC`
   - Processor: `MIPS`
   - Compiler: `GCC`
5. Click OK and wait for analysis to complete

### 2. Navigate to Known Functions

After analysis, use the **Function Graph** or **Listing** view:

| Address | Function | Description |
|---------|----------|-------------|
| `0x00132630` | main_flow | Most called - likely file I/O utility |
| `0x001321c8` | path_handler | References DFDATAS strings |
| `0x0019fb34` | data_loader | References DATA.DF addresses |
| `0x001a0a38` | file_ref | References DFDATAS in .sdata |
| `0x0023d468` | data_access | Secondary data reference |

### 3. Search for String References

To find where strings are used:

1. Press `G` to go to address
2. Enter `0x00556a28` (DATA.DF string)
3. Look for XREFs (cross-references) to find functions using this string

### 4. Analyze Call Graph

To verify callers:

1. Select a function in the Listing view
2. Press `X` to show cross-references
3. Look for `CALL` instructions from known caller addresses

## Useful Shortcuts

| Key | Action |
|-----|--------|
| `G` | Go to address |
| `X` | Show cross-references |
| `/` | Search |
| `;` | Add comment |
| `F5` | Refresh display |

## Verification with PCSX2 (Optional)

1. Set breakpoint at `0x00132630` in PCSX2 debugger
2. Run game to trigger data loading
3. Verify function is called and matches analysis

## Notes

- The ELF is stripped (no symbol names)
- Function names above are inferred from behavior
- Use string references as anchors for disassembly
'''
    return guide


def main() -> int:
    output_dir = Path(".local/ghidra")
    output_dir.mkdir(parents=True, exist_ok=True)

    script = generate_ghidra_script()
    script_path = output_dir / "ICOAnalysisScript.java"
    script_path.write_text(script)
    print(f"Ghidra script written to: {script_path}")

    guide = generate_markdown_guide()
    guide_path = output_dir / "GHIDRA_IMPORT_GUIDE.md"
    guide_path.write_text(guide)
    print(f"Import guide written to: {guide_path}")

    print(f"\nNext steps:")
    print(f"1. Download Ghidra from https://github.com/NationalSecurityAgency/ghidra")
    print(f"2. Import .local/extracted/SCUS_971.13.elf")
    print(f"3. Optionally import ICOAnalysisScript.java for quick navigation")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())