// GeneratedRoomRoleTables.h - verified ICO USA per-room primary-handler
// repertoires collected from PCSX2 runtime captures (Rev.159).
//
// AUTO-GENERATED by tools/extract_room_role_tables.py - do not edit by hand.
// Re-run the tool after adding a runtime capture.
//
// Per sceneId (the room being entered, init_scene_gobj a0):
//   roleCount = number of DISTINCT GObj pool addresses that carried this
//   handler as primary (isys_gobj_proc_add a3==1) during that room segment.
// The GObj pool is reused across rooms; these are pool-address counts, not
// host GObj handles. Host pairing is a documented HOST heuristic.
#pragma once

#include "core/gobj_abi.h"

namespace ico::engine {

struct VerifiedRoomRole {
    ico_ptr32 handlerAddr;
    const char* handlerName;
    u16 roleCount;
};

struct VerifiedRoomRolePlan {
    u16 sceneId;
    const VerifiedRoomRole* roles;
    u16 roleCount;
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene01[] = {
    {0x001CE6F0u, "type6_hB", 6u},
    {0x0023D518u, "type60_hB", 5u},
    {0x001C1DD8u, "boy_hB", 1u},
    {0x001EF980u, "seffect_hB", 1u},
    {0x001F3A00u, "runtime_1F3A00", 1u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene03[] = {
    {0x0023D518u, "type60_hB", 5u},
    {0x001BC530u, "type24_hB", 1u},
    {0x001C1DD8u, "boy_hB", 1u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene04[] = {
    {0x001F1CF0u, "torch_hB", 14u},
    {0x001D00F8u, "flag_hB", 10u},
    {0x0023D518u, "type60_hB", 10u},
    {0x001930B0u, "generator_hB", 4u},
    {0x001F3A00u, "runtime_1F3A00", 4u},
    {0x0018ECC8u, "chain_hB", 2u},
    {0x001BC1A8u, "type22_hB", 2u},
    {0x001C1DD8u, "boy_hB", 2u},
    {0x001CE3C0u, "enemy1_hB", 2u},
    {0x001CE760u, "enemy1_hD", 2u},
    {0x001D17F8u, "girl_hB", 2u},
    {0x001D1AD0u, "girl_hD", 2u},
    {0x001EF980u, "seffect_hB", 2u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene05[] = {
    {0x001D00F8u, "flag_hB", 10u},
    {0x0023D518u, "type60_hB", 10u},
    {0x001F1CF0u, "torch_hB", 6u},
    {0x0018ECC8u, "chain_hB", 2u},
    {0x001C1DD8u, "boy_hB", 2u},
    {0x001EF980u, "seffect_hB", 2u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene06[] = {
    {0x0023D518u, "type60_hB", 6u},
    {0x001C1DD8u, "boy_hB", 1u},
    {0x001D17F8u, "girl_hB", 1u},
    {0x001D1AD0u, "girl_hD", 1u},
    {0x001D1CF8u, "type55_hB", 1u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene07[] = {
    {0x0023D518u, "type60_hB", 9u},
    {0x001BA330u, "ap1_hB", 5u},
    {0x00197078u, "bird_hB", 3u},
    {0x001D3A30u, "ItemGeo", 3u},
    {0x001F1CF0u, "torch_hB", 3u},
    {0x001CE3C0u, "enemy1_hB", 2u},
    {0x001CE760u, "enemy1_hD", 2u},
    {0x001930B0u, "generator_hB", 1u},
    {0x001C0538u, "woodbox0_hB", 1u},
    {0x001C1DD8u, "boy_hB", 1u},
    {0x001D17F8u, "girl_hB", 1u},
    {0x001D1AD0u, "girl_hD", 1u},
    {0x001EA5E8u, "type15_hB", 1u},
    {0x001EF980u, "seffect_hB", 1u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene28[] = {
    {0x001D00F8u, "flag_hB", 5u},
    {0x0023D518u, "type60_hB", 5u},
    {0x001C1DD8u, "boy_hB", 1u},
    {0x001CE3C0u, "enemy1_hB", 1u},
    {0x001CE760u, "enemy1_hD", 1u},
    {0x001D17F8u, "girl_hB", 1u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene29[] = {
    {0x0023D518u, "type60_hB", 5u},
    {0x001CE6F0u, "type6_hB", 4u},
    {0x001C1DD8u, "boy_hB", 1u},
    {0x001EF980u, "seffect_hB", 1u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene2A[] = {
    {0x0023D518u, "type60_hB", 5u},
    {0x001CE6F0u, "type6_hB", 3u},
    {0x001C1DD8u, "boy_hB", 1u},
    {0x001D00F8u, "flag_hB", 1u},
    {0x001F1CF0u, "torch_hB", 1u},
    {0x001F3A00u, "runtime_1F3A00", 1u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene2B[] = {
    {0x001D00F8u, "flag_hB", 5u},
    {0x001F1CF0u, "torch_hB", 5u},
    {0x001F44C8u, "type36_hB", 5u},
    {0x0023D518u, "type60_hB", 5u},
    {0x001CE6F0u, "type6_hB", 3u},
    {0x0010D070u, "type39_hB", 1u},
    {0x001BC1A8u, "type22_hB", 1u},
    {0x001C1DD8u, "boy_hB", 1u},
};

constexpr VerifiedRoomRole kVerifiedRoomRolesScene2D[] = {
    {0x0023D518u, "type60_hB", 5u},
    {0x001D00F8u, "flag_hB", 4u},
    {0x001F1CF0u, "torch_hB", 4u},
    {0x001F44C8u, "type36_hB", 4u},
    {0x001CE6F0u, "type6_hB", 3u},
    {0x001BC530u, "type24_hB", 1u},
    {0x001C1DD8u, "boy_hB", 1u},
};

constexpr std::size_t kVerifiedRoomRolePlanCount = 11;

constexpr VerifiedRoomRolePlan kVerifiedRoomRolePlans[] = {
    {0x01u, kVerifiedRoomRolesScene01, 5u},
    {0x03u, kVerifiedRoomRolesScene03, 3u},
    {0x04u, kVerifiedRoomRolesScene04, 13u},
    {0x05u, kVerifiedRoomRolesScene05, 6u},
    {0x06u, kVerifiedRoomRolesScene06, 5u},
    {0x07u, kVerifiedRoomRolesScene07, 14u},
    {0x28u, kVerifiedRoomRolesScene28, 6u},
    {0x29u, kVerifiedRoomRolesScene29, 4u},
    {0x2Au, kVerifiedRoomRolesScene2A, 6u},
    {0x2Bu, kVerifiedRoomRolesScene2B, 8u},
    {0x2Du, kVerifiedRoomRolesScene2D, 7u},
};

}  // namespace ico::engine
