// GeneratedSceneTables.h — verified ICO USA scene tables.
//
// AUTO-GENERATED by tools/extract_scene_tables.py — do not edit by hand.
// Re-run the tool after changing sources; all values are raw bytes from
// .local/extracted/SCUS_971.13.elf.
//
// Descriptors: 0x2a31b8 stride 0x64 (68).
// Entries:     0x2a4c48 stride 0x4c.
// World range: 0x5f2fb8 + scene*0x194, [+0x128 start, +0x12C end).
// Entries emitted for scene(s): 0x0F, 0x2B.
#pragma once

#include "core/gobj_abi.h"

namespace ico::engine {

struct VerifiedSceneDescriptor {
    u16 descriptorIndex;
    u32 gate_44;
    ico_ptr32 processCallback_40;
    ico_ptr32 processCallback_58;
    ico_ptr32 vtable_60;
    const char* name;
};

struct VerifiedSceneEntry {
    u16 entryIndex;
    u8 descriptorIndex;
    u8 listId;
    u8 gobjType;
    u16 flag_44;
    ico_ptr32 processCallback_24;
    ico_ptr32 userData_30;
    u16 processArgument_40;
};

struct VerifiedSceneRange {
    u8 sceneId;
    u16 startEntry;
    u16 endEntry;
};

constexpr std::size_t kVerifiedSceneDescriptorCount = 68;
constexpr std::size_t kVerifiedSceneRangeCount = 97;

constexpr VerifiedSceneDescriptor kVerifiedSceneDescriptors[] = {
    {0, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, "NULL"},
    {1, 0x00000001u, 0x00153478u, 0x001C1A98u, 0x00202A60u, "BOY"},
    {2, 0x00000001u, 0x00174BA0u, 0x001D1668u, 0x00202A60u, "GIRL"},
    {3, 0x00000001u, 0x00000000u, 0x001D1668u, 0x00000000u, "GIRLDEMOCTRL"},
    {4, 0x00000001u, 0x00164440u, 0x001CE220u, 0x00202A60u, "ENEMY1"},
    {5, 0x00000001u, 0x00000000u, 0x001CE220u, 0x00000000u, "ENEMY_TEST"},
    {6, 0x00000001u, 0x00000000u, 0x001CEB18u, 0x00000000u, "DEMOMOTCTRL"},
    {7, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "SOBJ"},
    {8, 0x00000001u, 0x00000000u, 0x001AEA60u, 0x0023D660u, "PSOBJ"},
    {9, 0x00000001u, 0x00000000u, 0x001F17B0u, 0x00000000u, "TREE"},
    {10, 0x00000001u, 0x00000000u, 0x001F2048u, 0x00000000u, "TORCH"},
    {11, 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, "PARTICLE"},
    {12, 0x00000001u, 0x00000000u, 0x001E8EB8u, 0x00000000u, "PARTLAYOUT"},
    {13, 0x00000001u, 0x00000000u, 0x001F0568u, 0x00000000u, "LIGHTBIT"},
    {14, 0x00000001u, 0x00000000u, 0x001F36F0u, 0x00000000u, "WEAPON"},
    {15, 0x00000001u, 0x00000000u, 0x001EA278u, 0x00000000u, "SPIDER_LAYOUT"},
    {16, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "SOFA"},
    {17, 0x00000001u, 0x0017D1D0u, 0x001C00C0u, 0x0023D660u, "WOODBOX01"},
    {18, 0x00000001u, 0x00000000u, 0x001E9F08u, 0x00000000u, "ROTOBJECT"},
    {19, 0x00000001u, 0x00000000u, 0x001D27A8u, 0x00000000u, "BARREL"},
    {20, 0x00000001u, 0x00000000u, 0x001E8F38u, 0x00000000u, "ROPE"},
    {21, 0x00000001u, 0x00000000u, 0x0018E5B0u, 0x00000000u, "CHAIN"},
    {22, 0x00000001u, 0x00000000u, 0x001C09C8u, 0x00000000u, "FLEVER"},
    {23, 0x00000001u, 0x00000000u, 0x001C09C8u, 0x00000000u, "FLEVER_TRISTATE"},
    {24, 0x00000001u, 0x00000000u, 0x001C0C40u, 0x00000000u, "WLEVER"},
    {25, 0x00000001u, 0x00000000u, 0x001C0C40u, 0x00000000u, "WLEVER2"},
    {26, 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, "NONE"},
    {27, 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, "SV"},
    {28, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "CAMERADUMMY"},
    {29, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, "DUMMY"},
    {30, 0x00000001u, 0x00203EE8u, 0x00000000u, 0x0023D660u, "BGA"},
    {31, 0x00000001u, 0x00000000u, 0x001EF8E8u, 0x00000000u, "SEFFECT"},
    {32, 0x00000001u, 0x001971C0u, 0x00197240u, 0x001956E8u, "BIRD"},
    {33, 0x00000001u, 0x00000000u, 0x00193730u, 0x00192EB8u, "GENERATOR"},
    {34, 0x00000001u, 0x00000000u, 0x001C2FF0u, 0x00000000u, "CANDLE"},
    {35, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "MOBJ"},
    {36, 0x00000001u, 0x00000000u, 0x001F43D0u, 0x0023D660u, "DEMO_QSWORD"},
    {37, 0x00000001u, 0x00000000u, 0x001C34B8u, 0x0023D660u, "CHANDELIER"},
    {38, 0x00000001u, 0x00000000u, 0x001F62E8u, 0x00000000u, "WORM"},
    {39, 0x00000001u, 0x00000000u, 0x0010B2D0u, 0x00000000u, "POOL"},
    {40, 0x00000001u, 0x00000000u, 0x001CBD68u, 0x00000000u, "DARKVOLUME"},
    {41, 0x00000001u, 0x00000000u, 0x001E6968u, 0x00000000u, "MCOLTEST"},
    {42, 0x00000001u, 0x00000000u, 0x001E9910u, 0x0023D660u, "ROPEFIX"},
    {43, 0x00000001u, 0x00000000u, 0x001C2338u, 0x00000000u, "CAGE"},
    {44, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, "DYNAMICMOTIONDAT"},
    {45, 0x00000001u, 0x00000000u, 0x001CFB58u, 0x00000000u, "FLAG"},
    {46, 0x00000001u, 0x0019B7F8u, 0x0019A7E8u, 0x00199A60u, "QUEEN"},
    {47, 0x00000001u, 0x00000000u, 0x0019A7E8u, 0x00000000u, "QUEENDEMOCTRL"},
    {48, 0x00000001u, 0x00174BA0u, 0x001D1668u, 0x00202A60u, "DEVIL_GIRL"},
    {49, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "SKELTEST"},
    {50, 0x00000001u, 0x00000000u, 0x001C2FE8u, 0x0023D660u, "CAGEFIX"},
    {51, 0x00000001u, 0x00000000u, 0x001C92D8u, 0x00000000u, "CLOTHTEST"},
    {52, 0x00000001u, 0x00000000u, 0x0019BC58u, 0x0019BB60u, "QUEEN_BALL"},
    {53, 0x00000001u, 0x00000000u, 0x0019BAA8u, 0x0019B998u, "QUEEN_BARRIER"},
    {54, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, "STAGESETTING"},
    {55, 0x00000001u, 0x00000000u, 0x001D1C78u, 0x00000000u, "GIRLFORCEFIELD"},
    {56, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "INTEREST1"},
    {57, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "INTEREST3"},
    {58, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "INTEREST10"},
    {59, 0x00000001u, 0x00000000u, 0x00000000u, 0x0023D660u, "INTEREST20"},
    {60, 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, "KYOMI"},
    {61, 0x00000001u, 0x001BB6B0u, 0x001B8720u, 0x001BB3E0u, "AP1"},
    {62, 0x00000001u, 0x001BBF78u, 0x001BBE50u, 0x001BB988u, "ATTACKCHECKBOUND"},
    {63, 0x00000001u, 0x001BBF78u, 0x001BBB20u, 0x00000000u, "ATTACKCHECKBOUND"},
    {64, 0x00000001u, 0x00198140u, 0x00198218u, 0x001978B0u, "BOSS_CTRL"},
    {65, 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, "temp"},
    {66, 0x00000001u, 0x00000000u, 0x00191D08u, 0x00191C80u, "ENEMY_CONTROL"},
    {67, 0x00000001u, 0x00000000u, 0x001D03C8u, 0x00000000u, "FLY_INFO"},
};

constexpr VerifiedSceneRange kVerifiedSceneRanges[] = {
    {0x01, 41, 75},
    {0x4C, 75, 85},
    {0x02, 85, 108},
    {0x04, 108, 188},
    {0x05, 188, 214},
    {0x06, 214, 240},
    {0x07, 240, 283},
    {0x08, 283, 355},
    {0x09, 355, 429},
    {0x0A, 429, 506},
    {0x0B, 506, 599},
    {0x0C, 599, 695},
    {0x0D, 695, 738},
    {0x0E, 738, 790},
    {0x10, 790, 847},
    {0x0F, 847, 876},
    {0x11, 876, 938},
    {0x12, 938, 998},
    {0x13, 998, 1080},
    {0x14, 1080, 1164},
    {0x15, 1164, 1213},
    {0x1B, 1213, 1269},
    {0x1C, 1269, 1346},
    {0x1D, 1346, 1438},
    {0x1E, 1438, 1484},
    {0x1A, 1484, 1555},
    {0x16, 1555, 1616},
    {0x17, 1616, 1690},
    {0x1F, 1690, 1724},
    {0x21, 1724, 1740},
    {0x18, 1740, 1785},
    {0x20, 1785, 1833},
    {0x19, 1833, 1885},
    {0x22, 1885, 1919},
    {0x23, 1919, 1936},
    {0x24, 1936, 1966},
    {0x25, 1966, 2047},
    {0x26, 2047, 2063},
    {0x27, 2063, 2096},
    {0x29, 2096, 2124},
    {0x2A, 2124, 2151},
    {0x2B, 2151, 2176},
    {0x2C, 2176, 2192},
    {0x2D, 2192, 2249},
    {0x2E, 2249, 2303},
    {0x2F, 2303, 2339},
    {0x28, 2339, 2372},
    {0x30, 2372, 2382},
    {0x31, 2382, 2390},
    {0x32, 2390, 2421},
    {0x33, 2421, 2452},
    {0x34, 2452, 2464},
    {0x35, 2464, 2470},
    {0x36, 2470, 2494},
    {0x37, 2494, 2506},
    {0x38, 2506, 2522},
    {0x3A, 2522, 2568},
    {0x3B, 2568, 2629},
    {0x3C, 2629, 2691},
    {0x3D, 2691, 2694},
    {0x40, 2694, 2715},
    {0x3E, 2715, 2736},
    {0x41, 2736, 2747},
    {0x42, 2747, 2767},
    {0x44, 2767, 2770},
    {0x45, 2770, 2773},
    {0x46, 2773, 2776},
    {0x3F, 2776, 2812},
    {0x47, 2812, 2814},
    {0x48, 2814, 2816},
    {0x49, 2816, 2847},
    {0x4A, 2847, 2850},
    {0x4B, 2850, 2855},
    {0x5D, 2855, 2880},
    {0x5C, 2880, 2883},
    {0x5E, 2883, 2886},
    {0x5F, 2886, 2925},
    {0x60, 2925, 2954},
    {0x61, 2954, 3029},
    {0x62, 3029, 3078},
    {0x63, 3078, 3105},
    {0x64, 3105, 3160},
    {0x4E, 3160, 3170},
    {0x4F, 3170, 3195},
    {0x50, 3195, 3219},
    {0x4D, 3219, 3226},
    {0x51, 3226, 3247},
    {0x52, 3247, 3252},
    {0x53, 3252, 3285},
    {0x54, 3285, 3307},
    {0x55, 3307, 3313},
    {0x56, 3313, 3352},
    {0x5B, 3352, 3373},
    {0x57, 3373, 3390},
    {0x58, 3390, 3412},
    {0x59, 3412, 3444},
    {0x5A, 3444, 3453},
};

constexpr std::size_t kVerifiedScenePayloadCount = 54;
// Payload entries are grouped per scene in ascending scene id.
constexpr VerifiedSceneEntry kVerifiedScenePayload[] = {
    // scene 0x0F entry 847 desc 44 (DYNAMICMOTIONDAT) list 7 type 0
    {847, 44, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 848 desc 26 (NONE) list 7 type 0
    {848, 26, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 849 desc 26 (NONE) list 7 type 0
    {849, 26, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 850 desc 7 (SOBJ) list 7 type 0
    {850, 7, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 851 desc 7 (SOBJ) list 7 type 0
    {851, 7, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 852 desc 7 (SOBJ) list 7 type 0
    {852, 7, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 853 desc 7 (SOBJ) list 2 type 0
    {853, 7, 2, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 854 desc 7 (SOBJ) list 1 type 0
    {854, 7, 1, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 855 desc 7 (SOBJ) list 0 type 0
    {855, 7, 0, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 856 desc 7 (SOBJ) list 7 type 0
    {856, 7, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 857 desc 32 (BIRD) list 7 type 0
    {857, 32, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 858 desc 32 (BIRD) list 7 type 0
    {858, 32, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 859 desc 32 (BIRD) list 7 type 0
    {859, 32, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 860 desc 32 (BIRD) list 7 type 0
    {860, 32, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 861 desc 16 (SOFA) list 7 type 0
    {861, 16, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 862 desc 55 (GIRLFORCEFIELD) list 7 type 0
    {862, 55, 7, 0, 0x035D, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 863 desc 31 (SEFFECT) list 7 type 0
    {863, 31, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 864 desc 11 (PARTICLE) list 7 type 0
    {864, 11, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 865 desc 30 (BGA) list 7 type 0
    {865, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 866 desc 22 (FLEVER) list 7 type 0
    {866, 22, 7, 0, 0x0000, 0x00000000u, 0x00000002u, 0x0000},
    // scene 0x0F entry 867 desc 39 (POOL) list 7 type 0
    {867, 39, 7, 0, 0x0000, 0x00000000u, 0x00000013u, 0x0000},
    // scene 0x0F entry 868 desc 28 (CAMERADUMMY) list 7 type 0
    {868, 28, 7, 0, 0x0000, 0x0022B9A8u, 0x00000015u, 0x0000},
    // scene 0x0F entry 869 desc 30 (BGA) list 7 type 0
    {869, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 870 desc 30 (BGA) list 7 type 0
    {870, 30, 7, 0, 0x0000, 0x0022BCA8u, 0x00000015u, 0x0000},
    // scene 0x0F entry 871 desc 30 (BGA) list 7 type 0
    {871, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 872 desc 44 (DYNAMICMOTIONDAT) list 7 type 0
    {872, 44, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 873 desc 54 (STAGESETTING) list 7 type 0
    {873, 54, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 874 desc 30 (BGA) list 7 type 0
    {874, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x0F entry 875 desc 44 (DYNAMICMOTIONDAT) list 7 type 0
    {875, 44, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2151 desc 7 (SOBJ) list 7 type 0
    {2151, 7, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2152 desc 7 (SOBJ) list 7 type 0
    {2152, 7, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2153 desc 7 (SOBJ) list 7 type 0
    {2153, 7, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2154 desc 7 (SOBJ) list 7 type 0
    {2154, 7, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2155 desc 22 (FLEVER) list 7 type 0
    {2155, 22, 7, 0, 0x0000, 0x00000000u, 0x00000002u, 0x0000},
    // scene 0x2B entry 2156 desc 6 (DEMOMOTCTRL) list 7 type 0
    {2156, 6, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2157 desc 6 (DEMOMOTCTRL) list 7 type 0
    {2157, 6, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2158 desc 6 (DEMOMOTCTRL) list 7 type 0
    {2158, 6, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2159 desc 11 (PARTICLE) list 7 type 0
    {2159, 11, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2160 desc 39 (POOL) list 7 type 0
    {2160, 39, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2161 desc 30 (BGA) list 7 type 0
    {2161, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2162 desc 30 (BGA) list 7 type 0
    {2162, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2163 desc 30 (BGA) list 7 type 0
    {2163, 30, 7, 0, 0x0000, 0x0020F688u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2164 desc 30 (BGA) list 7 type 0
    {2164, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2165 desc 30 (BGA) list 7 type 0
    {2165, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2166 desc 30 (BGA) list 7 type 0
    {2166, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2167 desc 30 (BGA) list 7 type 0
    {2167, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2168 desc 30 (BGA) list 7 type 0
    {2168, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2169 desc 30 (BGA) list 7 type 0
    {2169, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2170 desc 30 (BGA) list 7 type 0
    {2170, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2171 desc 30 (BGA) list 7 type 0
    {2171, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2172 desc 30 (BGA) list 7 type 0
    {2172, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2173 desc 44 (DYNAMICMOTIONDAT) list 7 type 0
    {2173, 44, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2174 desc 54 (STAGESETTING) list 7 type 0
    {2174, 54, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
    // scene 0x2B entry 2175 desc 30 (BGA) list 7 type 0
    {2175, 30, 7, 0, 0x0000, 0x00000000u, 0x00000015u, 0x0000},
};

}  // namespace ico::engine

