# CMake generated Testfile for 
# Source directory: /home/hoper/Documentos/repos/ico-reconstruction/native
# Build directory: /home/hoper/Documentos/repos/ico-reconstruction/native/build-assert
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smoke "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/smoke_test")
set_tests_properties(smoke PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;163;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(gobj_pool "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/gobj_pool_test")
set_tests_properties(gobj_pool PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;164;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(isysgobj_runtime "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/isysgobj_runtime_test")
set_tests_properties(isysgobj_runtime PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;165;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(isysgobj_semantic "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/isysgobj_semantic_test")
set_tests_properties(isysgobj_semantic PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;166;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(isysgobj_semantic_runtime "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/isysgobj_semantic_runtime_test")
set_tests_properties(isysgobj_semantic_runtime PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;167;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(process_node_pool "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/process_node_pool_test")
set_tests_properties(process_node_pool PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;168;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(isysgobj_process "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/isysgobj_process_test")
set_tests_properties(isysgobj_process PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;169;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(slot_dispatch "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/slot_dispatch_test")
set_tests_properties(slot_dispatch PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;170;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(render_backend "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/render_backend_test")
set_tests_properties(render_backend PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;171;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(tm2 "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/tm2_test")
set_tests_properties(tm2 PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;172;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(gif_command "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/gif_command_test")
set_tests_properties(gif_command PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;173;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(gif_executor "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/gif_executor_test")
set_tests_properties(gif_executor PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;174;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(gif_packet "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/gif_packet_test")
set_tests_properties(gif_packet PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;175;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(scene_loader "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/scene_loader_test")
set_tests_properties(scene_loader PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;176;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(game_loop_scene "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/game_loop_scene_test")
set_tests_properties(game_loop_scene PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;177;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(girlbrain_semantic "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/girlbrain_semantic_test")
set_tests_properties(girlbrain_semantic PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;178;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(world_state_slot "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/world_state_slot_test")
set_tests_properties(world_state_slot PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;179;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(world_state_loader "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/world_state_loader_test")
set_tests_properties(world_state_loader PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;180;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(gobj_factory "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/gobj_factory_test")
set_tests_properties(gobj_factory PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;181;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(gobj_entity_allocator "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/gobj_entity_allocator_test")
set_tests_properties(gobj_entity_allocator PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;182;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
add_test(opengl_backend "/home/hoper/Documentos/repos/ico-reconstruction/native/build-assert/opengl_backend_test")
set_tests_properties(opengl_backend PROPERTIES  _BACKTRACE_TRIPLES "/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;187;add_test;/home/hoper/Documentos/repos/ico-reconstruction/native/CMakeLists.txt;0;")
