#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CURRENT_SESSION_FILE="$PROJECT_ROOT/.local/pcsx2-logs/current-session.env"

if [[ ! -f "$CURRENT_SESSION_FILE" ]]; then
  echo "ERROR: no current gameplay session manifest: $CURRENT_SESSION_FILE" >&2
  echo "Start a session with ./tools/run-ico-pcsx2-logpoints.sh first." >&2
  exit 1
fi

# Generated by run-ico-pcsx2-logpoints.sh using shell-escaped values.
source "$CURRENT_SESSION_FILE"

if [[ -z "${ICO_PCSX2_PROBE_LOG:-}" ]]; then
  echo "ERROR: current session manifest has no ICO_PCSX2_PROBE_LOG." >&2
  exit 1
fi

echo "Session: ${ICO_PCSX2_PROBE_SESSION:-unknown}"
echo "Monitoring: $ICO_PCSX2_PROBE_LOG"

exec python3 "$PROJECT_ROOT/tools/runtime-probe-analyzer/runtime_probe_analyzer.py" \
  --input "$ICO_PCSX2_PROBE_LOG" --follow
